### ISSUE TITLE
Node.js usage broken due to lowdash filename case

### ISSUE THREAD

**Issue by chrisl8** [heydenberk/stochator#38]
In order to use the current version of stachator in Node.js, after installing I had to edit  
`node_modules/stochator/build/index.js` and change:  
`var _lodashIsFunction = require("lodash.isFunction");`
to:
`var _lodashIsFunction = require("lodash.isfunction");`  

and  
`var _lodashIsString = require("lodash.isString");`
to:
`var _lodashIsString = require("lodash.isstring");`

Apparently the node.js versions of isFunction and isString are in lowercase in the filesystem.

**Comment by heydenberk** [comment]
Thanks again for the fix! It's merged.
